#!/sbin/busybox sh

cd /sbin

for i in $(./busybox --list)
do
	./busybox ln -s busybox $i
done

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

copySynapse() {
	cp /res/synapse/Synapse.apk /system/app/Synapse.apk
	chown 0.0 /system/app/Synapse.apk
	chmod 644 /system/app/Synapse.apk
}

loadRamdisk () {
	if [[ ! -f /data/nosynapse ]]; then
		if [[  ! -f /system/app/Synapse.apk ]]; then
			copySynapse
		else
			R5=$(md5sum < /res/synapse/Synapse.apk | tr -d ' -')
			S5=$(md5sum < /system/app/Synapse.apk | tr -d ' -')
			if [ $R5 != $S5 ]; then
				copySynapse
			fi
		fi
	fi

	umount -f /system
	umount -f /data

	rm /init
	mv -f /res/ramdisks/$1/* /

	exec /init
	exit
}

prepareKnox () {
	BP="/system/build.prop"

	if grep -q ro.config.tima=1 $BP; then
		sed -i "s/ro.config.tima=1/ro.config.tima=0/g" $BP
	fi

	if grep -q ro.build.selinux=1 $bp; then
		sed -i "s/ro.build.selinux=1/ro.build.selinux=0/g" $BP
	fi

	APKS="KNOXAgent.apk KNOXAgent.odex KnoxAttestationAgent.apk KnoxAttestationAgent.odex KNOXStore.apk KNOXStore.odex KNOXStub.apk ContainerAgent.apk ContainerAgent.odex"

	for APK in $APKS; do
		if [ -f /system/app/$APK ]; then
			rm /system/app/$APK
		fi
	done
}

mkdir /dev
mkdir /dev/block
mknod /dev/block/mmcblk0p20 b 259 12
mknod /dev/block/mmcblk0p21 b 259 13
mount -t ext4 /dev/block/mmcblk0p20 /system
mount -t ext4 /dev/block/mmcblk0p21 /data

if grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
	loadRamdisk sec43
fi

if [ -f /system/framework/twframework.jar ]; then
	if grep -q ro.build.version.release=4.3 /system/build.prop; then
		prepareKnox
		loadRamdisk sec43
	fi

	loadRamdisk sec43
else
	if grep -q ro.build.version.release=4.3 /system/build.prop; then
		cp -a /lib/modules/* /system/lib/modules/
		loadRamdisk aosp43
	fi

	cp -a /lib/modules/* /system/lib/modules/
	loadRamdisk aosp43
fi


